name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'


jobs:
  build_and_publish_docker_image:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Tag
        id: set_tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            # Берём первые 8 символов SHA-коммита
            SHORT_SHA=${{ github.sha | truncate(8) }}
            echo "TAG=$SHORT_SHA" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "create" || "${{ startsWith(github.ref_type, 'tag') }}" == "true" ]]; then
            # Используем полное имя тега
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "No valid event detected!"
          fi
        shell: bash

      - name: Show TAG Variable
        run: echo "Final Tag ${{ steps.set_tag.outputs.TAG }}"
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/netology-static-app:${{ steps.set_tag.outputs.TAG }}
          push: true
