name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'


jobs:
  build_and_publish_docker_image:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Docker tag
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Если это тег, используем его имя (удаляем 'refs/tags/')
            echo "DOCKER_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            # Если это коммит без тега, используем первые 8 символов SHA
            echo "DOCKER_TAG=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
          fi
          echo "Using tag: $DOCKER_TAG"
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/netology-static-app:${{ env.DOCKER_TAG }}
          push: true
